name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (without v prefix)'
        required: true
        default: '2.0.0'
      prerelease:
        description: 'Is this a pre-release?'
        required: false
        default: 'false'
        type: boolean

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      
      - name: Set version from input
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Update package.json version
        run: |
          # Use jq to update the version field in package.json
          jq '.version = "${{ github.event.inputs.version }}"' package.json > package.json.tmp
          mv package.json.tmp package.json
      
      - name: Build and create GitHub release
        run: |
          pnpm release -- --github-release --tag v${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: browser-extensions-v${{ github.event.inputs.version }}
          path: release/
          if-no-files-found: error 