name: Release Extension

on:
  push:
    # Trigger this workflow when a new tag is pushed
    tags:
      - 'v*' # Run when tag matches v*, like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm' # Caches pnpm dependencies
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build and create GitHub release
        run: pnpm release -- --github-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: browser-extensions
          path: release/
          if-no-files-found: error 